### ISSUE TITLE
New methods / extensions - Happy to write them

### ISSUE THREAD

**Issue by luke-hill** [sparklemotion/http-cookie#53]
Finding I need the following a lot. I've already written some of them straw man. Asking if you want them uploading to the gem proper and would accept PR's to add them?

Cookie
  - `#to_h` (Caster to enable pushing values back into Selenium readily)
  - `#expires` bug fix / extension to permit DateTime expiry values: #52 

CookieJar
  - `#include?` (Boolean checker)
  - `#cookie_named` (Detector)

**Comment by flavorjones** [comment]
Hi @luke-hill, thanks for starting this conversation and offering to contribute!

* `Cookie#to_h`:
  * This seems like a sensible feature to support, since cookies are just a bag of key/value pairs. Not sure what your current implementation does, but I think the PERSISTENT_PROPERTIES constant should probably be the set of keys in the hash, to keep it consistent with the YAML dump and load methods.
* `Cookie#expires`:
  * Thank you for the PR! I reviewed it.
* `CookieJar#include?`:
  * This already exists, though it may not be obvious. CookieJar includes [`Enumerable`](https://rubyapi.org/3.3/o/enumerable#method-i-include-3F) and so we get it for free.
* `CookieJar#cookie_named`:
  * Can you say more about your use case here? Is the implementation similar to `jar.cookies.find_all { |c| c.name == "foo" }`?

**Comment by luke-hill** [comment]
Hi there.

So `#include?` I have written as detecting it based on the name prop. This errors currently when checking the cookie jar.

So my method is cookie_jar.include?('foo') which looks inside the jar and checks whether (Using #any?), whether there is any cookie with the :name prop

cookie_named is the same as above, but using detect to return the first matcher

**Comment by luke-hill** [comment]
Sounds great. I'm actually not going to be looking at this for a while. Because I'm off for a few days. I'll copy and paste my monkeypatch file and stuff I've been working on so you can see what I can do / need then I'll adapt / work on things on my return unless some of it has been priorly done

```
# frozen_string_literal: true

module HTTP
  class Cookie
    # this is a rudimentary fix for the one we did, so ignore this
    def expires=(t)
      t = t.to_time
      @max_age = nil
      @session = t.nil?
      @expires = t
    end
    
    # this allows me to cast something into a format I can then inject into Selenium. So I have 2 way conversions working reliably (i.e. take selenium cookie, save as http cookie, and vice versa - I'm not 100% sure this is a reliable answer, so it might need adapting)
    def to_h
      {
        name: name,
        value: value,
        path: path,
        secure: secure,
        expires: expires
      }
    end
  end
end

module HTTP
  class CookieJar
    # I actually made this when I "thought" I could do a create unless it's already there action. However for my single use case so far, the cookie will NEVER be there, because you cannot create cookies X-Domain. So for now this method has no use for me personally.
    def cookie_named(name)
      cookies.detect { |cookie| cookie.name == name }
    end

    # This method was the companion to the above. For some reason the regular `#include?` doesn't work and gives a weird error relating to `[]` not being manipulable. I cannot remember explicitly if I was doing something wrong or not. Maybe I was :man_shrugging: 
    def include?(cookie_name)
      cookies.any? { |cookie| cookie.name == cookie_name }
    end
  end
end
```

**Comment by flavorjones** [comment]
Seems like a reasonable start! I'm going to close this issue, but please do open PRs when you get time, I'd be happy to review and help get these ideas merged. ❤️
